DROP DATABASE IF EXISTS BD_HISTORIA_INTERACTIVA;
CREATE DATABASE BD_HISTORIA_INTERACTIVA;
USE BD_HISTORIA_INTERACTIVA;

CREATE TABLE JUGADORES
 (
    ID_JUGADOR  INTEGER NOT NULL,			
    NOMBRE_JUGADOR  VARCHAR(21) NOT NULL,		
    FECHA_REGISTRO  VARCHAR(22) NOT NULL				
 );

 CREATE TABLE PARTIDAS
 (
    ID_PARTIDA  INTEGER NOT NULL,		
    ID_JUGADOR  INTEGER NOT NULL,    		
    FECHA_INICIO DATE NOT NULL,	
    FECHA_FIN DATE NOT NULL,
    MINUTOS_JUGADOS INTEGER NOT NULL
);

 CREATE TABLE FINALES
 (
    ID_FINAL  INTEGER NOT NULL,				
    NOMBRE_FINAL VARCHAR(255)  NOT NULL, 
    DESCRIPCION_FINAL VARCHAR(255) NOT NULL
 );


 CREATE TABLE CAMINOS
 (
    ID_CAMINO  INTEGER NOT NULL,			
    NOMBRE_CAMINO VARCHAR(255) NOT NULL, 
    OBSERVACIONES_CAMINO VARCHAR(255) NOT NULL
 );

  CREATE TABLE NODOS
 (
    ID_NODO  INTEGER NOT NULL,
    ID_CAMINO INTEGER NOT NULL,
    ID_PARTIDA INTEGER NOT NULL
 );

  CREATE TABLE FINALES_ALCANZADOS
 (
    ID_PARTIDA  INTEGER NOT NULL,
    ID_FINAL INTEGER NOT NULL
 );


 ALTER TABLE JUGADORES ADD
    PRIMARY KEY ( ID_JUGADOR );

 ALTER TABLE PARTIDAS ADD
    PRIMARY KEY ( ID_PARTIDA );

 ALTER TABLE FINALES ADD
    PRIMARY KEY ( ID_FINAL );

ALTER TABLE CAMINOS ADD
    PRIMARY KEY ( ID_CAMINO );

 ALTER TABLE NODOS ADD
    PRIMARY KEY ( ID_NODO );


ALTER TABLE PARTIDAS ADD CONSTRAINT `ES_JUGADO_POR` FOREIGN KEY (`ID_JUGADOR`) REFERENCES `JUGADORES`(`ID_JUGADOR`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE NODOS ADD CONSTRAINT `PERTENECE_A` FOREIGN KEY (`ID_PARTIDA`) REFERENCES `PARTIDAS`(`ID_PARTIDA`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE NODOS ADD CONSTRAINT `FORMA_PARTE_DEL` FOREIGN KEY (`ID_CAMINO`) REFERENCES `CAMINOS`(`ID_CAMINO`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FINALES_ALCANZADOS ADD CONSTRAINT `DENTRO_DE_LA` FOREIGN KEY (`ID_PARTIDA`) REFERENCES `PARTIDAS`(`ID_PARTIDA`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FINALES_ALCANZADOS ADD CONSTRAINT `TIENE` FOREIGN KEY (`ID_FINAL`) REFERENCES `FINALES`(`ID_FINAL`) ON DELETE CASCADE ON UPDATE CASCADE;
